#define CLI_RED     "\x1b[31m"
#define CLI_GREEN   "\x1b[32m"
#define CLI_YELLOW  "\x1b[33m"
#define CLI_BLUE    "\x1b[34m"
#define CLI_MAGENTA "\x1b[35m"
#define CLI_CYAN    "\x1b[36m"
#define CLI_WHITE   "\x1b[0m"
